import React from "react";
import { ArrowRight, Upload, Leaf, Globe, Zap, Heart } from "lucide-react";

interface LandingHeroProps {
  onStart: (action: "upload" | "analyze") => void;
}

export default function LandingHero({ onStart }: LandingHeroProps) {
  const heroImageSrc = "/src/assets/images/living_room_hero_1780929723048.png";

  return (
    <div className="min-h-[92vh] flex flex-col justify-center py-12 px-6 sm:px-12 lg:px-24 max-w-7xl mx-auto">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        
        {/* Texts Left */}
        <div className="lg:col-span-7 space-y-8">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#A3B18A]/20 border border-[#A3B18A]/30 text-[#556B2F] text-xs font-semibold uppercase tracking-wider font-mono">
            <Leaf className="w-3.5 h-3.5" />
            AI-POWERED INTERIOR AUDITING
          </div>

          <div className="space-y-4">
            <h1 className="text-5xl sm:text-6xl font-bold font-display tracking-tight text-[#2F2F2F] leading-[1.08]">
              EcoDesign <span className="text-[#556B2F]">AI</span>
            </h1>
            <p className="text-2xl font-semibold tracking-tight text-[#C96A4A] font-display italic">
              "Design Smarter. Live Greener."
            </p>
            <p className="text-[#8D8B87] text-lg leading-relaxed max-w-2xl font-light">
              An artificial intelligence companion for modern architectural design. 
              Upload room images to automatically scan decorative fabrics, detect carbon footprints, 
              grade material lifecycle scores, and obtain low-VOC energy and water refurbishing suggestions.
            </p>
          </div>

          {/* Quick Metrics Bar */}
          <div className="grid grid-cols-3 gap-4 py-4 border-y border-[#8D8B87]/20 font-mono">
            <div>
              <div className="text-2xl font-bold text-[#556B2F]">42%+</div>
              <div className="text-[11px] text-[#8D8B87] uppercase tracking-wider">Carbon Saving Potential</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-[#C96A4A]">88+</div>
              <div className="text-[11px] text-[#8D8B87] uppercase tracking-wider">Average Eco-Score</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-[#2F2F2F]">₹32,000</div>
              <div className="text-[11px] text-[#8D8B87] uppercase tracking-wider">Annual Energy Saving</div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-4">
            <button
              onClick={() => onStart("upload")}
              className="flex items-center justify-center gap-2.5 px-8 py-4 bg-[#556B2F] hover:bg-[#556B2F]/90 text-[#F8F6F2] font-semibold rounded-xl text-base shadow-lg shadow-[#556B2F]/20 hover:shadow-xl hover:shadow-[#556B2F]/30 transition-all cursor-pointer group"
            >
              <Upload className="w-5 h-5 group-hover:-translate-y-0.5 transition-transform" />
              Upload Room Image
            </button>
            <button
              onClick={() => onStart("analyze")}
              className="flex items-center justify-center gap-2.5 px-8 py-4 bg-white hover:bg-[#E8DCCB]/25 text-[#2F2F2F] border border-[#8D8B87]/30 font-semibold rounded-xl text-base transition-all cursor-pointer group"
            >
              Analyze Sustainability
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform text-[#C96A4A]" />
            </button>
          </div>

          {/* Supported Core Pillars */}
          <div className="flex items-center gap-6 pt-4 text-xs text-[#8D8B87] font-mono">
            <span className="flex items-center gap-1.5">
              <Globe className="w-3.5 h-3.5 text-[#556B2F]" />
              SDG 11, 12, 13
            </span>
            <span className="flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5 text-[#C96A4A]" />
              IoT Integration
            </span>
            <span className="flex items-center gap-1.5">
              <Heart className="w-3.5 h-3.5 text-[#A3B18A]" />
              Low VOC Healthy Spaces
            </span>
          </div>
        </div>

        {/* Feature Image Right */}
        <div className="lg:col-span-5 relative">
          <div className="absolute inset-0 bg-[#A3B18A] rounded-2xl rotate-3 opacity-10 blur-xl"></div>
          <div className="relative border-4 border-white rounded-3xl overflow-hidden shadow-2xl shadow-[#556B2F]/10 transform transition-transform hover:scale-[1.01] duration-300">
            <img
              src={heroImageSrc}
              alt="Eco-friendly living space concept generated by Gemini"
              className="w-full h-[500px] object-cover"
              referrerPolicy="no-referrer"
            />
            
            {/* Image Floater Widget - Sustainability Rating */}
            <div className="absolute bottom-6 left-6 right-6 p-4 rounded-2xl bg-white/80 backdrop-blur-md border border-white/40 flex items-center justify-between shadow-lg">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[#556B2F] flex items-center justify-center text-white">
                  <Leaf className="w-5 h-5" />
                </div>
                <div>
                  <div className="text-xs text-[#8D8B87] font-mono uppercase tracking-wider">Sustainability Rating</div>
                  <div className="text-sm font-bold text-[#2F2F2F]">Bamboo & Natural Lime-clay Loft</div>
                </div>
              </div>
              <div className="text-right">
                <span className="text-lg font-bold text-[#556B2F] font-mono">88 / 100</span>
                <span className="block text-[10px] text-[#A3B18A] font-semibold font-mono uppercase">Grade A+</span>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
